version: '3.3'

services:
  db-1:
    image: mysql:latest
    container_name: mysql-container-1
    environment:
      - MYSQL_ROOT_PASSWORD=tanio
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  db-2:
    image: mysql:latest
    container_name: mysql-container-2
    environment:
      - MYSQL_ROOT_PASSWORD=tanio
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password